### ISSUE TITLE
Add urlencode/urldecode

### ISSUE THREAD

**Issue by vbolshakovmodescoru** [radiopapus/bezzabot#12]
Please add urlencode/urldecode functionality like b64e/b64d.

**Comment by radiopapus** [comment]
Есть несколько вариантов api для команды. Можно сделать универсальную команду вместо b64e/b64d сделать enc/dec.
Пример:
```
enc -f b64 {{text}}
dec -f b64 {{text}}
enc -f url {{url}}
dec -f url {{url}}
```
или же добавить urlencode/urldecode как запрошено. Мне больше нравится вариант с универсальной командой.

**Comment by radiopapus** [comment]
https://github.com/radiopapus/bezzabot/pull/17

**Comment by radiopapus** [comment]
I have already deployed it to production so you can try it as you wish.

**Comment by vbolshakovmodescoru** [comment]
> I have already deployed it to production so you can try it as you wish.

Yeah, it works fine, thank you!
